### ISSUE TITLE
Events Page Broken Again

### ISSUE THREAD

**Issue by StrangeWill** [chadev/chadev.github.io#102]
apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.93YTExoueec.O/m=client/…d=1/am=AQ/rs=AGLTcCOmk9lc2N8jOZZeMfbwpU1b__boCg/t=zcms/cb=gapi.loaded_0:38
    
    Uncaught TypeError: Cannot read property 'replace' of undefined

Dunno why, isn't related to PR #101, happens on my github pages which currently doesn't include that branch.

**Comment by StrangeWill** [comment]
This has broken what, twice in the past month (see PR #86), does Google just hate us?

**Comment by StrangeWill** [comment]
I have layout changes on events so I'll probably fix this tonight...

**Comment by keathley** [comment]
So is this a regression or something new?

**Comment by StrangeWill** [comment]
If I had to wager a complete guess, Google is returning something as undefined and we're trying to execute something against it and gapi is smashing my stack trace. :(

I'll investigate after work.

**Comment by StrangeWill** [comment]
PR #103, as guessed description is coming back undefined on one of the most recent added events, protected against that.

**Comment by StrangeWill** [comment]
PR accepted, closing. Thanks!
