### ISSUE TITLE
One of our dependencies has an open CVE

### ISSUE THREAD

**Issue by vendion** [chadev/chadev.github.io#194]
The version of `nekogiri` that is depended on (either directly or indirectly) has an open CVE and should be updated.

See https://github.com/chadev/chadev.github.io/network/alert/Gemfile.lock/nokogiri/open for details.

**Comment by juzten** [comment]
For anyone that wants to work on this issue for an easy PR, you should be able to run `bundle update nokogiri` to update to a newer version

**Comment by ModdedGamers** [comment]
Working on this now.;

**Comment by vendion** [comment]
This should have been addressed by #207
