### ISSUE TITLE
Group Image Display Options

### ISSUE THREAD

**Issue by StrangeWill** [chadev/chadev.github.io#70]
Do we want to keep copies of logos, or enforce that groups get a gravatar?

**Comment by juzten** [comment]
After just dealing with this, I vote to have an alternate option for gravatar. I don't have an email address for the Chadev Python meetup group so I can't make a gravatar image for the group. I'll take a stab at making an alternate option that takes in any url.

**Comment by kylegordy** [comment]
@juzten Building it in a way to take any image is easy, the hard part is making sure everyone uses the right size image. I guess we could list it in the docs and check the images upon a pull request?

**Comment by vendion** [comment]
I would say we should keep the images on an external service, but doesn't have to be in Gravatar per say either.  This way we just reference either a URL or some unique identifier, allowing the group image to be changed without needing to add the new logo to the repo and/or updating anything on the site.

If image hosting becomes an issue I'm sure we could figure something out.  One thing we do lose by moving away from Gravatar is the assurance that the images we get back will be the same size.

**Comment by StrangeWill** [comment]
> One thing we do lose by moving away from Gravatar is the assurance that the images we get back will be the same size.

@vendion or not replaced with 404s, or not replaced with shock images, or not terribly slow to load.

I personally like the option of adding it to the code base and approval of the dimensions via a pull request (shoot, can we automate a failing build on that?).

**Comment by vendion** [comment]
@StrangeWill Yeah I did say *one* there are many things that we could encounter that could have negative/unwanted effects towards the site or our image as a community.

**Comment by keathley** [comment]
I'll vote and say that unless anyone has a really compelling reason not to we should just check them into the repo. It's not like we have so many groups joining that we can't enforce the size rules manually. Lets just make sure that any rules or constraints about images end up in CONTRIBUTING.md file.



Chris Keathley

**Comment by vendion** [comment]
I agree that we currently don't have ton of groups or anything, but I'm also wanting to try to future proof things so we don't have to rework this later on down the road.  If everything thinks having the images in the repo wouldn't be too much to manage then I'm game.

**Comment by keathley** [comment]
eh, YAGNI.  Lets roll agile style and cross that bridge when it's burning underneath us.

**Comment by StrangeWill** [comment]
Well ideally we'd have a Ruby site and groups would be managed in the database and images on a file system.  :smirk:

**Comment by vendion** [comment]
@keathley I see you like to live dangerously :smile:
