### ISSUE TITLE
Custom Plugins Not Supported By Github Pages

### ISSUE THREAD

**Issue by StrangeWill** [chadev/chadev.github.io#95]
Was going to add a section for our meetups and repository for files (still working out issues with plugins not working as advertised with Jekyll, and more specifically Liquid acting up). Then @acedrew mentioned that Github only whitelists a handful of Ruby plugins.

Ughhh.

So are we going to plow ahead with more Jekyll and look into rolling our own build setup outside of Github (some kind of Jenkins CI thing?), or do we want to explore getting of Jekyll and I shouldn't waste my time?

Really without having outside plugin support and not even being able to use popular 3rd party plugins will really hamper us from doing awesome things with Jekyll.

**Comment by StrangeWill** [comment]
@keathley Heroku doesn't support static pages, we can do some Ruby hackery, but I'd like to stay away.

Any other preferred hosts? Till then I'm going to run with my github-hack deploy for prototyping layouts and showing them off.

**Comment by keathley** [comment]
digital ocean is my preferred (and it makes sense since they are a lunch sponsor-ish)

**Comment by StrangeWill** [comment]
Various working deploy branches, we can just rework it when we get to the point of doing that.
