### ISSUE TITLE
Events Page UI

### ISSUE THREAD

**Issue by StrangeWill** [chadev/chadev.github.io#98]
Heard this was one of the things we want to work on, so far I got... uh... this.

![Screenshot](http://i.imgur.com/x3RzlMJ.png)
http://strangewill.github.io/events/

But I'm kind of at a loss of what to do at this point, I've considered making it a calendar layout with pop-outs when tapping(mobile) or hovering (desktop), but not sure if that's worth it (let me know if you think that's a good approach and I'll tackle it).

Any suggestions on direction/features? I could do all kinds of sorting/searching (languages/groups hosting/etc) but I don't have any concepts of any of those things from Google Calendars, it'll mean more when we start doing meetup integrations (if ever).

**Comment by keathley** [comment]
I say ditch the borders.  Potentially tweak the line heights, but other then that I think that should be fine.  @kylegordy what are your thoughts?

**Comment by kylegordy** [comment]
@StrangeWill Thanks for hacking on this :+1: I agree with @keathley the borders should go and the line height could use some work. Other than that I say push it! I can always hop in and nerd out on the design :)

**Comment by StrangeWill** [comment]
Tweaked, submitted at PR #104
