### ISSUE TITLE
Resources Page

### ISSUE THREAD

**Issue by StrangeWill** [chadev/chadev.github.io#99]
Biggest thing that'll help moving that forward is knowing what other things other than just community resources that we want on there.

Any suggestions for categories? Maybe some getting-started tutorials for languages? Some tool chains? Anything?

**Comment by keathley** [comment]
I'm not sure what we're trying to accomplish with the resources page.  Is it chattanooga based resources?  Or is it developer resources?  Does the second even make sense to have on our site?

**Comment by kylegordy** [comment]
@keathley I was thinking it could be a Chattanooga based one. Though, I'm not sure now if it warrants it's own page. I can't think of many local resources to add to it. What do you all think? Should we remove it?

**Comment by keathley** [comment]
I'm fine with removing it for now.

**Comment by kylegordy** [comment]
Yeah, I think that makes sense. We can always build it out later.

**Comment by kylegordy** [comment]
Commit #113 resolved this.
